#/*(cb*/
#/**************************************************************************
# *
# *     Copyright (c) 1992, 1995 Intel Corporation.  All rights reserved.
# *
# *
# * Intel hereby grants you permission to copy, modify, and distribute this
# * software and its documentation.  Intel grants this permission provided
# * that the above copyright notice appears in all copies and that both the
# * copyright notice and this permission notice appear in supporting
# * documentation.  In addition, Intel grants this permission provided that
# * you prominently mark as not part of the original any modifications made
# * to this software or documentation, and that the name of Intel
# * Corporation not be used in advertising or publicity pertaining to the
# * software or the documentation without specific, written prior
# * permission.
# *
# * Intel provides this AS IS, WITHOUT ANY WARRANTY, INCLUDING THE WARRANTY
# * OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, and makes no
# * guarantee or representations regarding the use of, or the results of the
# * use of, the software and documentation in terms of correctness,
# * accuracy, reliability, currentness, or otherwise, and you rely on the
# * software, documentation, and results solely at your own risk.
# *
# **************************************************************************/
#/*)ce*/

#*****************************************************************************
# Makefile for hdil.a -- Host Debugger Interface Library
#
# HDIL is used by a host (e.g., a debugger) to communicate with Mon960.
#
#*****************************************************************************

# Essential under System V, harmless elsewhere
SHELL = /bin/sh

#-----------  DEFAULTS  ---------------------------
TARG	= hdil.a
CFLAGS  = $(OPT) -I$(IDIR) $(HOSTDEFS) $(DEBUG) 
O 	= o
RM	= rm -f
CP	= cp
#DEBUG   = -DDEBUG -g -O0
OPT	= -g
IDIR 	= ../../include
IOPT	= -O
AR	= ar cvr $(TARG) $(OBJS)
RANLIB	= ranlib
DEST	= $(G960BASE)/lib

#-----------------------------------------------------------------------------
#		Uncomment for Sun4
#__sun4__#HOSTDEFS	= -DUSG -DHOST
#-----------------------------------------------------------------------------
#		Uncomment for Solaris
#__sol-sun4__#HOSTDEFS	= -DUSG -DHOST
#__sol-sun4__#RANLIB	= echo >/dev/null
#-----------------------------------------------------------------------------
#		Uncomment for system V / i386  (release 4)
#__i386vr4__#HOSTDEFS	= -DUSG -DHOST
#__i386vr4__#RANLIB	= echo >/dev/null
#-----------------------------------------------------------------------------
#		Uncomment for RS/6000
#__rs6000__#HOSTDEFS	= -DUSG -DPOSIX -DHOST
#-----------------------------------------------------------------------------
#		Uncomment for HP-UX (hp 9000/700)
#__hp700__#HOSTDEFS	= -DUSG -DHOST
#__hp700__#RANLIB	= echo >/dev/null
#-----------------------------------------------------------------------------
#		Uncomment for HP-UX (hp 9000/300)
#__hp9000__#HOSTDEFS	= -DUSG -DHOST
#__hp9000__#RANLIB	= echo >/dev/null
#-----------------------------------------------------------------------------
#		Uncomment for MS/DOS
# Customized for Metaware's DOS compiler and Phar Lap's DOS-Extender.
#
#__dos__#TARG		= hdil.lib
#__dos__#O 		= obj
#__dos__#RM 		= del
#__dos__#CP 		= copy
#__dos__#HOSTDEFS	= -DMSDOS -DHOST -fsoft -Heol=10
#__dos__#CC 		= HC386
#__dos__#OPT		= -g
#__dos__#NOLINK		= -c
#__dos__#IOPT 		= -O3
#__dos__#RANLIB 	= @echo 
#__dos__#AR		= 386lib $(TARG) -create -twocase @makelib.mw
#__dos__#DEST		=$(G960BASE,/=\)\lib
#-----------------------------------------------------------------------------
#		Uncomment for Windows 95
# Customized for Microsoft C 9.00 (Visual C++ 2.0)
#
#__win95__#TARG		= hdil.lib
#__win95__#O		= obj
#__win95__#HOSTDEFS	= -DWIN95 -DMSDOS -DHOST
#__win95__#CC		= CL
#__win95__#OPT		= -Zi
#__win95__#NOLINK		= -c
#__win95__#IOPT		= -O2
#__win95__#RANLIB		= @echo 
#__win95__#AR		= lib /OUT:$(TARG) @makelib.mw
#__win95__#DEST		= $(G960BASE,/=\)\lib
#-----------------------------------------------------------------------------

OBJS	= download.$O hostcmds.$O serve.$O init.$O brkpoint.$O \
	  trgt_go.$O memcache.$O regs.$O eeprom.$O \
	  extendn.$O errlist.$O misc.$O aplink.$O gmu.$O

$(TARG): $(OBJS) makelib.mw
	$(RM) $(TARG)
	$(AR)
	$(RANLIB) $(TARG)

makelib.mw:
#__dos__#	!foreach i $(OBJS)
#__dos__#		echo -add $i >>makelib.mw
#__dos__#	!end
#__win95__#	!foreach i $(OBJS)
#__win95__#		echo $i >>makelib.mw
#__win95__#	!end

# generate with sun: cc -M -I../include *.c
$(OBJS): private.h common.h hdil.h hdi_com.h hdi_regs.h hdi_errs.h \
	 hdi_mcfg.h hdi_brk.h hdi_arch.h hdi_stop.h dbg_mon.h hdi_regs.h \
	 hdi_gmu.h

#-----------------------------------------------------------------------------
#		'STANDARD' GNU/960 TARGETS BELOW THIS POINT
#-----------------------------------------------------------------------------

# 'G960BASE' should be defined at invocation
# Avoid explicit use of "/" in pathnames, since DOS version needs "\"
install:
	make clean
	make $(TARG) OPT=$(INSTOPT)
	(cd $(DEST) ; $(RM) $(TARG))
	$(CP) $(TARG) $(DEST)


# Separate lines required in order for DOS version to work
#
clean:
	$(RM) $(TARG)
	$(RM) *.$O
	$(RM) makelib.mw	# DOS -- doesn't hurt anybody else
	$(RM) *.rex		# DOS -- doesn't hurt anybody else

#-----------------------------------------------------------------------------
# Target to uncomment host-specific lines in this makefile, i.e. lines
# beginning in column 1 with the following string:  #__<hostname>__# .
# Original Makefile is backed up as 'Makefile.old'.
#
# Invoke with:  make make HOST=xxx
#-----------------------------------------------------------------------------
make:
	-@grep -s "^#The next line was generated by 'make make'" Makefile; \
	if test $$? = 0 ; then	\
		echo "Makefile has already been processed with 'make make'";\
		exit 1; \
	elif test $(HOST)x = x ; then \
		echo 'Specify "make make HOST=???"'; \
		exit 1; \
	else \
		mv -f Makefile Makefile.old; \
		echo "#The next line was generated by 'make make'"> Makefile; \
		echo "HOST=$(HOST)"				 >> Makefile; \
		echo						 >> Makefile; \
		sed "s/^#__$(HOST)__#//" < Makefile.old		 >> Makefile; \
		if test $(HOST) = dos; then mv Makefile makefile; \
			mv Makefile.old makefile.unx; \
                fi \
	fi
