#*****************************************************************************
# Makefile for toolib.a -- host code shared by more than one tool
#
#*****************************************************************************

# Essential under System V, harmless elsewhere
SHELL = /bin/sh

TARG	= toolib.a
IDIR	= ../../include
CFLAGS  = $(OPT) $(HOSTDEFS) -I$(IDIR) -DHOST=$(HOSTNM)

#
# Add the following to CFLAGS:
# -Dmalloc=ldmalloc -Drealloc=ldrealloc -Dfree=ldfree
# to enable linker heap debug code.
#

#-----------  DEFAULTS  ---------------------------
O 	= o
RM	= rm -f
CP	= cp
OPT	= -g
IOPT	= -O
NOLINK	= -c
HOSTNM	= \"$(HOST)\"
AR	= ar cvr $(TARG) $(OBJS)
RANLIB	= ranlib
DEST	= $(G960BASE)/lib
HOSTOBJS=
OBJS	= $(HOSTOBJS) cmdout.$O cstrip.$O getopt.$O getopt1.$O g960td.$O i_files.$O put_page.$O rdmconf.$O respfile.$O ttybreak.$O ttyflush.$O fpoint.$O tlibver.$O

#-----------------------------------------------------------------------------
#		Uncomment for GCC960 HOSTED toolib
#
# Please see instructions in the gld960 makefile for more information.
#
#__gcc960__#TARGET   = cycx
#__gcc960__#CC       = gcc960 -Fcoff -Tm$(TARGET) -fsigned-char -mic-compat -DHOST_SYS=GCC960_SYS -traditional
#__gcc960__#AR       = gar960 rvc $(TARG) $(OBJS)
#__gcc960__#RANLIB   = echo >/dev/null
#__gcc960__#OBJS     = put_page.$O respfile.$O mktemp.$O g960td.$O cmdout.$O fpoint.$O
#-----------------------------------------------------------------------------
#		Uncomment for system V / i386 (release 4)
#__i386vr4__#HOSTDEFS	= -DUSG -DHOST_SYS=i386_SYSV_SYS
#__i386vr4__#RANLIB	= echo >/dev/null
#-----------------------------------------------------------------------------
#               Uncomment for Solaris 5.1 on the sun4 (sol-sun4).
#__sol-sun4__#HOSTDEFS	= -DUSG -DHOST_SYS=i386_SYSV_SYS
#__sol-sun4__#RANLIB	= echo >/dev/null
#-----------------------------------------------------------------------------
#		Uncomment for system V / i386  (release 3.2)
#__i386v__#HOSTDEFS	= -DUSG -DHOST_SYS=i386_SYSV_SYS
#__i386v__#RANLIB	= echo >/dev/null
#-----------------------------------------------------------------------------
#		Uncomment for system V / 68020v (NCR Tower)
#__68020v__#HOSTDEFS	= -DUSG -Dtower_68k -DHOST_SYS=NCR_SYSV_SYS
#__68020v__#RANLIB	= echo >/dev/null
#-----------------------------------------------------------------------------
#		Uncomment for Decstation
#__dec3100__#HOSTDEFS	= -DDEC3100 -DHOST_SYS=DEC3100_SYS
#-----------------------------------------------------------------------------
#		Uncomment for RS/6000
#__rs6000__#HOSTDEFS	= -DUSG -DPOSIX -DRS6000 -DHOST_SYS=AIX_SYS -DUSG -qchars=signed
#-----------------------------------------------------------------------------
#		Uncomment for Apollo 400
#__ap400__#HOSTDEFS	= -A nansi -DHOST_SYS=APOLLO400_SYS
#-----------------------------------------------------------------------------
#		Uncomment for HP9000-300
#__hp9000__#HOSTDEFS	= -DUSG -DHOST_SYS=HP9000_SYS
#__hp9000__#RANLIB	= echo >/dev/null
#__hp9000__#OPT		= 
#-----------------------------------------------------------------------------
#		Uncomment for HP9000-700
#__hp700__#HOSTDEFS	= -DUSG -DHOST_SYS=HP9000_SYS
#__hp700__#RANLIB	= echo >/dev/null
#__hp700__#OPT		= 
#-----------------------------------------------------------------------------
#		Uncomment for MS/DOS
#  Set up for 386|DOS-Extender (Phar Lap) with Metaware 3.x compiler
#__dos__#TARG		= toolib.lib
#__dos__#O 			= obj
#__dos__#RM 		= del
#__dos__#CP 		= copy
#__dos__#HOSTNM 	= "dos"
#__dos__#HOSTDEFS 	= -DUSG -DDOS -DHOST_SYS=DOS_SYS
#__dos__#HOSTOBJS 	= dos_sysv.obj dosport.obj dosproc.obj mktemp.obj
#__dos__#OPT 		= -g 
#__dos__#IOPT 		= -O3 
#__dos__#RANLIB 	= @echo 
#__dos__#AR			= 386lib $(TARG) -create -twocase @objlist
#__dos__#DEST		=$(G960BASE,/=\)\lib
#__dos__#I_DIR   	=$(IDIR,/=\)
#__dos__#AS			= 386ASM
#__dos__#ASFLAGS	= -twocase
#__dos__#CC         = HC386
#__dos__#CFLAGS  	= -w1 -fsoft -Heol=10 $(OPT) $(HOSTDEFS) -I$(IDIR) -DHOST=$(HOSTNM)
#__dos__#DOSXP		= c:\tnt
#__dos__#DOSXN		= $(DOSXP)\bin\gotnt.exe
#-----------------------------------------------------------------------------
#		Uncomment for Windows 95
#__win95__#TARG		= toolib.lib
#__win95__#O		= obj
#__win95__#HOSTDEFS	= -W2 -DWIN95 -DUSG -DDOS -DHOST_SYS=DOS_SYS
#__win95__#HOSTOBJS	= dos_sysv.obj dosproc.obj winport.obj
#__win95__#OPT		= -Zi
#__win95__#IOPT		= -O2
#__win95__#RANLIB		= @echo
#__win95__#AR		= lib /OUT:$(TARG) @objlist.lbc
#__win95__#DEST		=$(G960BASE,/=\)\lib
#__win95__#I_DIR		=$(IDIR,/=\)
#__win95__#CC		= CL
#-----------------------------------------------------------------------------
# 		Uncomment for Sun 3
#__sun3__#HOSTDEFS	= -DHOST_SYS=SUN3_SYS
#-----------------------------------------------------------------------------
# 		Uncomment for Sun 386i
#__sun386i__#HOSTDEFS	= -DHOST_SYS=SUN3_SYS
#-----------------------------------------------------------------------------
# 		Uncomment for Sun 4
#__sun4__#HOSTDEFS	= -DHOST_SYS=SUN4_SYS
#-----------------------------------------------------------------------------
# 		Uncomment for Vax-Ultrix
#__vax-ultrix__#HOSTDEFS	= -DHOST_SYS=VAX_ULTRIX_SYS
#-----------------------------------------------------------------------------


.c.$O:
	$(CC) $(NOLINK) $(CFLAGS) $<

$(TARG): objlist.lbc hc.pro $(OBJS) 
	$(RM) $(TARG)
	$(AR)
	$(RANLIB) $(TARG)

objlist.lbc:
#__win95__#	!foreach i $(OBJS)
#__win95__#		echo $i >> objlist.lbc
#__win95__#	!end
#__dos__#	!foreach i $(OBJS)
#__dos__#		echo -add $i >> objlist.lbc
#__dos__#	!end

hc.pro:
#__dos__#	$(CP) $(I_DIR)\sys\hc.pro hc.pro
#__win95__#	@echo


cmdout.$O:	$(IDIR)/i_toolib.h
cstrip.$O:	$(IDIR)/sysv.h
dos_sysv.$O:	$(IDIR)/gnudos.h
dosport.$O:	$(IDIR)/gnudos.h $(IDIR)/ttycntl.h
dosproc.$O:	$(IDIR)/gnudos.h
getopt1.$O:	$(IDIR)/getopt.h
i_files.$O:	$(IDIR)/i_toolib.h
nindy.$O:	$(IDIR)/block_io.h $(IDIR)/demux.h
nindy.$O:	$(IDIR)/gnudos.h $(IDIR)/sysv.h $(IDIR)/ttycntl.h $(IDIR)/wait.h
respfile.$O:	$(IDIR)/i_toolib.h
ttybreak.$O:	$(IDIR)/ttycntl.h
ttyflush.$O:	$(IDIR)/ttycntl.h


#-----------------------------------------------------------------------------
#		'STANDARD' GNU/960 TARGETS BELOW THIS POINT
#-----------------------------------------------------------------------------

VERSTR1 = echo "	\"$(TARG) `cat _version`, `date`\";"
#__dos__#VERSTR1 = =verstr $(TARG) _version
#__win95__#VERSTR1 = =verstr $(TARG) _version

tlibver.$O: FORCE
#__dos__#tlibver.obj: verstr.exe
#__win95__#tlibver.obj: verstr.exe
	$(RM) tlibver.c
	echo static char toolib_ver[]=	 > tlibver.c
	$(VERSTR1) 			>> tlibver.c
	$(CC) $(CFLAGS) -c tlibver.c
 
FORCE:

#__win95__#verstr.exe .REREAD: verstr.c
#__win95__#	$(CC) -o verstr.exe verstr.c
#__win95__#
#__dos__#verstr.exe .REREAD: verstr.c
#__dos__#	$(CC) -nomap -nostub verstr.c
#__dos__#	copy /b $(DOSXN)+verstr.exp verstr.exe


# 'G960BASE' should be defined at invocation
# Avoid explicit use of "/" in pathnames, since DOS version needs "\"
install:
	make $(TARG) OPT="$(IOPT)" DOSXP=$(DOSXP) DOSXN=$(DOSXN)
	(cd $(DEST) ; $(RM) $(TARG))
	$(CP) $(TARG) $(DEST)
#__dos__#	(cd $(DEST); $(RM) $(TARG)$(EXP))
#__dos__#	$(CP) $(TARG)$(EXP) $(DEST)
#__win95__#	(cd $(DEST); $(RM) verstr.exe)
#__win95__#	$(CP) verstr.exe $(DEST)
#__dos__#	(cd $(DEST); $(RM) verstr.exe)
#__dos__#	$(CP) verstr.exe $(DEST)
#__dos__#	(cd $(DEST); $(RM) verstr.exp)
#__dos__#	$(CP) verstr.exp $(DEST)

install_ctools:	install

# Separate lines required in order for DOS version to work
#
clean:
	$(RM) $(TARG)
	$(RM) *.$O
	$(RM) core
	$(RM) objlist.lbc	# DOS -- doesn't hurt anybody else
	$(RM) *.rex		# DOS -- doesn't hurt anybody else
	$(RM) verstr.exp	# DOS -- doesn't hurt anybody else
	$(RM) verstr.exe	# DOS -- doesn't hurt anybody else
	$(RM) hc.pro		# DOS -- doesn't hurt anybody else

#-----------------------------------------------------------------------------
# Target to uncomment host-specific lines in this makefile, i.e. lines
# beginning in column 1 with the following string:  #__<hostname>__# .
# Original Makefile is backed up as 'Makefile.old'.
#
# Invoke with:  make make HOST=xxx
#-----------------------------------------------------------------------------
make:
	-@grep -s "^#The next line was generated by 'make make'" Makefile; \
	if test $$? = 0 ; then	\
		echo "Makefile has already been processed with 'make make'";\
		exit 1; \
	elif test $(HOST)x = x ; then \
		echo 'Specify "make make HOST=???"'; \
		exit 1; \
	else \
		mv -f Makefile Makefile.old; \
		echo "#The next line was generated by 'make make'"> Makefile;\
		echo "HOST=$(HOST)"				 >> Makefile; \
		echo						 >> Makefile; \
		sed "s/^#__$(HOST)__#//" < Makefile.old		 >> Makefile; \
		if test $(HOST) = dos; then mv Makefile makefile; fi \
	fi
