
NO_SRC = echo No source code is shipped for this tool.

install:
	$(NO_SRC)

install_coff:
	$(NO_SRC)

install_bout:
	$(NO_SRC)

install_cfbe:
	$(NO_SRC)

install_libh_coff:
	$(NO_SRC)

clean:
	$(NO_SRC)
