#-----------------------------------------------------------------------------
#			Makefile for gdmp960
#
# $Id: Makefile,v 1.48 1995/10/02 19:40:40 whitmore Exp $
#-----------------------------------------------------------------------------

# Essential under System V, harmless elsewhere
SHELL = /bin/sh

ITARG	= dmp960
TARG	= gdmp960
IDIR	= ../../include
LDIR	= $(G960BASE)/lib
CFLAGS	= $(OPT) -I$(IDIR) $(HOSTDEFS)

#-----------  DEFAULTS  ---------------------------
O	= o
RM	= rm -f
CP	= cp
MV	= mv
LN	= ln
STRIP	= strip
OPT	= -g
IOPT	= -O
OUT	= -o
NOLINK	= -c
DEST	= $(G960BASE)/bin

#-----------------------------------------------------------------------------
#		Uncomment for system V (i386v).
#__i386v__#HOSTDEFS = -DHOST_SYS=i386_SYSV_SYS
#-----------------------------------------------------------------------------
#               Uncomment for system V release 4 (i386vr4).
#__i386vr4__#HOSTDEFS = -DHOST_SYS=i386_SYSV_SYS
#-----------------------------------------------------------------------------
#		Uncomment for NCR System V (68020v).
#__68020v__#HOSTDEFS = -DHOST_SYS=NCR_SYSV_SYS
#-----------------------------------------------------------------------------
#		Uncomment for HP9000-300
#__hp9000__#HOSTDEFS = -DHOST_SYS=HP9000_SYS
#-----------------------------------------------------------------------------
#		Uncomment for HP9000-700
#__hp700__#HOSTDEFS = -DHOST_SYS=HP9000_SYS
#-----------------------------------------------------------------------------
#		Uncomment for Apollo 400
#__ap400__#HOSTDEFS = -A nansi -DAPOLLO_400 -DHOST_SYS=APOLLO400_SYS
#-----------------------------------------------------------------------------
#		Uncomment for RS/6000
#__rs6000__#HOSTDEFS = -DPOSIX -qchars=signed -DHOST_SYS=AIX_SYS
#__rs6000__#LDFLAGS = -b nodelcsect
#-----------------------------------------------------------------------------
#		Uncomment for Sun 3
#__sun3__#HOSTDEFS = -DHOST_SYS=SUN3_SYS
#__sun3__#LDFLAGS  = -Bstatic
#-----------------------------------------------------------------------------
#		Uncomment for Sun 386i
#__sun386i__#HOSTDEFS = -DHOST_SYS=SUN3_SYS
#__sun386i__#LDFLAGS  = -Bstatic
#-----------------------------------------------------------------------------
#		Uncomment for Sun 4
#__sun4__#HOSTDEFS = -DHOST_SYS=SUN4_SYS
#__sun4__#LDFLAGS  = -Bstatic
#-----------------------------------------------------------------------------
#		Uncomment for Solaris on the sun4 (sol-sun4).
#__sol-sun4__#HOSTDEFS  = -DSOLARIS -DHOST_SYS=i386_SYSV_SYS
#__sol-sun4__#LDFLAGS = -Bstatic
#-----------------------------------------------------------------------------
#		Uncomment for DOS
#__dos__#O		= obj
#__dos__#EXE		= .exe
#__dos__#EXP		= .exp
#__dos__#RM		= del
#__dos__#CP		= copy
#__dos__#MV		= ren
#__dos__#LN		= copy
#__dos__#STRIP		= echo
#__dos__#		# Strip is no-op;  might want dtrim instead someday
#__dos__#HOSTDEFS	= -DDOS -DHOST_SYS=DOS_SYS
#__dos__#I_DIR		= $(IDIR,/=\)
#__dos__#OPT		= -g
#__dos__#IOPT		= -O3
#__dos__#CC		= HC386
#__dos__#CFLAGS		= -w1 -fsoft $(OPT) -I$(IDIR) $(HOSTDEFS) 
#__dos__#LDFLAGS	= "-stack 10000h" "-maxreal 0ffffh" 
#__dos__#LDFLAGS2	=  -fsoft -twocase -nomap -nostub
#__dos__#OUT		= -e
#__dos__#DEST		= $(G960BASE,/=\)\bin
#__dos__#DOSXP		= c:\tnt
#__dos__#DOSXN		= $(DOSXP)\bin\gotnt.exe
#__dos__#CFIG           = $(DOSXP)\bin\cfig386
#__dos__#CFIGFLAGS      = -saveregs -maxvcpimem 0 -vmfile vmmdrv.exp
#-----------------------------------------------------------------------------
#		Uncomment for Windows 95
#__win95__#O		= obj
#__win95__#EXE		= .exe
#__win95__#LN		= copy
#__win95__#STRIP		= echo
#__win95__#HOSTDEFS	= -W2 -DWIN95 -DDOS -DHOST_SYS=DOS_SYS
#__win95__#I_DIR		= $(IDIR,/=\)
#__win95__#OPT		= -Zi
#__win95__#IOPT		= -O2
#__win95__#CC		= CL
#__win95__#OUT		= -o
#__win95__#DEST		= $(G960BASE,/=\)\bin
#-----------------------------------------------------------------------------

OBJS	= gdmp960.$O boutdmp.$O coffdmp.$O dwarfdmp.$O elfdmp.$O \
	    objmap.$O names.$O print.$O ver960.$O
LIBS    = $(LDIR)/libbfd.a $(LDIR)/toolib.a $(LDIR)/libdwarf.a

#__dos__#LIBS	= $(LDIR)/libbfd.lib $(LDIR)/toolib.lib $(LDIR)/libdwarf.lib
#__win95__#LIBS	= $(LDIR)/libbfd.lib $(LDIR)/toolib.lib $(LDIR)/libdwarf.lib

all: $(TARG)

.c.$O:
	$(CC) $(NOLINK) $(CFLAGS) $<

$(ITARG): $(TARG)
	$(MV) $(TARG)$(EXE) $(ITARG)$(EXE)
#__dos__#	$(MV) $(TARG)$(EXP) $(ITARG)$(EXP)

$(TARG): hc.pro objlst.rf $(OBJS) $(LIBS)
#__dos__#	!if $(HOST) == dos
#__dos__#		$(CC) $(CFLAGS) -o $(TARG) $(LDFLAGS) @objlst.rf
#__dos__#		copy /b $(DOSXN)+$(TARG)$(EXP) $(TARG)$(EXE)
#__dos__#       	$(CFIG) $(TARG) $(CFIGFLAGS)
#__dos__#	!else
		$(CC) $(CFLAGS) -o $(TARG) $(LDFLAGS) $(OBJS) $(LIBS)
#__dos__#	!endif

hc.pro:
#__dos__#       $(CP) $(I_DIR)\sys\hc.pro hc.pro
#__win95__#	@echo

objlst.rf:
#__dos__#	echo $(LDFLAGS2) >> objlst.rf
#__dos__#	!foreach i $(OBJS)
#__dos__#		echo $(i) >> objlst.rf
#__dos__#	!end
#__dos__#	!foreach i $(LIBS)
#__dos__#		echo -l$(i) >> objlst.rf
#__dos__#	!end
#__win95__#	@echo

$(OBJS):	gdmp960.h
gdmp960.$O:	$(IDIR)/bfd.h $(IDIR)/libdwarf.h $(IDIR)/dwarf2.h
boutdmp.$O:	$(IDIR)/bout.h
coffdmp.$O:	$(IDIR)/coff.h
elfdmp.$O:	$(IDIR)/elf.h
dwarfdmp.$O:	$(IDIR)/libdwarf.h $(IDIR)/dwarf2.h dwarfdmp.h
print.$O:	dwarfdmp.h
names.$O:	dwarfdmp.h

#-----------------------------------------------------------------------------
#		'STANDARD' GNU/960 TARGETS BELOW THIS POINT
#-----------------------------------------------------------------------------

ver960.o: FORCE
	$(RM) ver960.c
	echo static char gnu960_ver[]=	 		 > ver960.c
	echo "\"Intel 80960 Dumper/Disassembler, `cat _version`, `date`\";" >> ver960.c
	echo \#include \"ver960.h\"			>> ver960.c
	$(CC) $(CFLAGS) -c ver960.c

# DOS version
ver960.obj: FORCE
	$(RM) ver960.c
	echo static char gnu960_ver[]=	 	 > ver960.c
	=$(LDIR)/verstr "Intel 80960 Dumper/Disassembler" _version	>> ver960.c
	echo \#include "ver960.h"		>> ver960.c
	$(CC) $(CFLAGS) -c ver960.c

# Dummy target to force execution of dependent targets.
#
FORCE:


# 'G960BASE' will be defined at invocation
install:
	make LDIR=$(LDIR) $(TARG) OPT="$(IOPT)" DOSXP=$(DOSXP) DOSXN=$(DOSXN)
	-$(STRIP) $(TARG)$(EXE)
	(cd $(DEST); $(RM) $(TARG)$(EXE))
	$(CP) $(TARG)$(EXE) $(DEST)
#__dos__#	(cd $(DEST); $(RM) $(TARG)$(EXP))
#__dos__#	$(CP) $(TARG)$(EXP) $(DEST)

install_ctools:
	make install TARG="$(ITARG)"

# Separate lines required in order for DOS version to work
#
clean:
	$(RM) *.$O
	$(RM) $(ITARG)$(EXE)
	$(RM) $(TARG)$(EXE)
	$(RM) core
	$(RM) *.rex		# for DOS, doesn't hurt anybody else
	$(RM) hc.pro		# for DOS, doesn't hurt anybody else
	$(RM) objlst.rf 	# for DOS, doesn't hurt anybody else
	$(RM) *.exp		# for DOS, doesn't hurt anybody else


#-----------------------------------------------------------------------------
# Target to uncomment host-specific lines in this makefile, i.e. lines
# beginning in column 1 with the following string:  #__<hostname>__# .
# Original Makefile is backed up as 'Makefile.old'.
#
# Invoke with:  make make HOST=xxx
#-----------------------------------------------------------------------------
make:
	-@grep -s "^#The next line was generated by 'make make'" Makefile; \
	if test $$? = 0 ; then	\
		echo "Makefile has already been processed with 'make make'";\
		exit 1; \
	elif test $(HOST)x = x ; then \
		echo 'Specify "make make HOST=???"'; \
		exit 1; \
	else \
		mv -f Makefile Makefile.old; \
		echo "#The next line was generated by 'make make'"> Makefile;\
		echo "HOST=$(HOST)"				 >> Makefile; \
		echo						 >> Makefile; \
		sed "s/^#__$(HOST)__#//" < Makefile.old		 >> Makefile; \
		if test $(HOST) = dos; then mv Makefile makefile; fi \
	fi
